spring:
  profiles: qa

# Logging
logging:
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
  level:
    root: INFO
    com.training.mjunction.usersvcs: INFO
    org.springframework: INFO
    org.hibernate: INFO
 