spring:
  profiles: dev

# Logging
logging:
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
  level:
    root: DEBUG
    com.training.mjunction.usersvcs: DEBUG
    org.springframework: ERROR
    org.hibernate: DEBUG
    sun.rmi: ERROR
    org.reflections: ERROR
    sun.reflect: ERROR
    org.apache.coyote.http11: ERROR
    org.glassfish.jersey.internal.util: ERROR

 
