spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: update

# Logging
logging:
  pattern:
    console: "[%-5level] %date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %logger{15}#%line %msg\n"
  level:
    root: DEBUG
    com.training.mjunction.usersvcs: DEBUG
    org.springframework: NONE
    org.hibernate: DEBUG
    sun.rmi.loader: ERROR
    org.reflections: ERROR
 